### PR TITLE
fix: correctly encode multihashes with serde

### PR DESCRIPTION
**Pull request by Stebalien**
The number of digest bytes written needs to match the size.

See the upstream issue here: https://github.com/multiformats/rust-multihash/pull/140

The one change is to not allocate.

### CODE REVIEW

**Comment by Stebalien** [comment]
Note: I'm not _entirely_ sure if this is the correct fix. At a minimum, we shouldn't be writing the extra bytes. But I'm not sure if just spitting out the buffer without calling `encode` is correct.

**Comment by Stebalien** [comment]
And it's definitely a breaking change.

**Comment by johnchandlerburnham** [comment]
Looking at the upstream issue, this makes sense to me, and resolves some of the confusion I had around truncation. Not 100% sure it's completely right either, but it seems more right than what exists currently, so in the interest of moving fast I've merged it.

Do the other multihash implementations do truncation correctly? Would be useful to compare if so

**Comment by Stebalien** [comment]
> Do the other multihash implementations do truncation correctly? Would be useful to compare if so

Yes. My concern here is whether or not this is supposed to be encoded as a _multihash_ or as something else. Specifically, should the digest be length-prefixed, or written as raw bytes.

**Comment by johnchandlerburnham** [comment]
I'm pretty sure it should be encoded as a multihash, as per https://github.com/multiformats/multihash/issues/133

**Pull request merged**
